version: "3"

services:
  nats-streaming-server:
    image: nats-streaming:latest
    container_name: nats-streaming-server
    restart: unless-stopped
    command: "-m 8222"
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - app-network

  nats-streaming-console:
    image: kuali/nats-streaming-console:latest
    container_name: nats-streaming-console
    restart: unless-stopped
    ports:
      - "8282:8282"
    # TODO: Adjust original image to allow environment override for docker-compose
    # environment:
    #   - STAN_URL=nats://nats-streaming-server:4222
    #   - STAN_MONITOR_URL=http://nats-streaming-server:8222
    depends_on:
      - nats-streaming-server
    networks:
      - app-network

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
    networks:
      - app-network

  graphql:
    build:
      context: ../graphql/
      dockerfile: Dockerfile
    image: graphql
    container_name: graphql
    restart: always
    ports:
      - "50040:50040"
    environment:
      - NATS_STREAMING_URL=nats://nats-streaming-server:4222
    depends_on:
      - nats-streaming-server
    networks:
      - app-network

networks:
  app-network:
