version: "3"

services:
  nats-streaming-server:
    image: nats-streaming:latest
    container_name: nats-streaming-server
    restart: unless-stopped
    command: "-m 8222"
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - app-network

  nats-streaming-console:
    image: kuali/nats-streaming-console:latest
    container_name: nats-streaming-console
    restart: unless-stopped
    ports:
      - "8282:8282"
    # TODO: Adjust original image to allow environment override for docker-compose
    # environment:
    #   - STAN_URL=nats://nats-streaming-server:4222
    #   - STAN_MONITOR_URL=http://nats-streaming-server:8222
    depends_on:
      - nats-streaming-server
    networks:
      - app-network

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - app-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
    networks:
      - app-network

  grpc:
    build:
      context: ../grpc/
      dockerfile: Dockerfile
    image: grpc
    container_name: grpc
    restart: always
    ports:
      - "50041:50041"
    environment:
      - DB_PRIMARY_DSN=host=postgres port=5432 user=root dbname=root password=root sslmode=disable
      - DB_REPLICA_DSN=host=postgres port=5432 user=root dbname=root password=root sslmode=disable
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_SAMPLER_TYPE=const
    depends_on:
      - postgres
      - jaeger
    networks:
      - app-network

  graphql:
    build:
      context: ../graphql/
      dockerfile: Dockerfile
    image: graphql
    container_name: graphql
    restart: always
    ports:
      - "50040:50040"
    environment:
      - NATS_URL=nats://nats-streaming-server:4222
      - NATS_CLUSTER=test-cluster
      - GRPC_URL=grpc:50041
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_SAMPLER_TYPE=const
    depends_on:
      - nats-streaming-server
      - grpc
    networks:
      - app-network

  worker:
    build:
      context: ../worker/
      dockerfile: Dockerfile
    image: worker
    container_name: worker
    restart: always
    environment:
      - NATS_STREAMING_URL=nats://nats-streaming-server:4222
      - NATS_CLUSTER=test-cluster
      - GRPC_URL=grpc:50041
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_SAMPLER_TYPE=const
    depends_on:
      - jaeger
      - nats-streaming-server
      - grpc
    networks:
      - app-network

networks:
  app-network:
