// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: sandbox_sales_v1.proto

package sandbox_sales_v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetSaleOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSaleOrderRequest) Reset() {
	*x = GetSaleOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sandbox_sales_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSaleOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaleOrderRequest) ProtoMessage() {}

func (x *GetSaleOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sales_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaleOrderRequest.ProtoReflect.Descriptor instead.
func (*GetSaleOrderRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_sales_v1_proto_rawDescGZIP(), []int{0}
}

func (x *GetSaleOrderRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSaleOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SaleOrder *SaleOrder `protobuf:"bytes,1,opt,name=sale_order,json=saleOrder,proto3" json:"sale_order,omitempty"`
}

func (x *GetSaleOrderResponse) Reset() {
	*x = GetSaleOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sandbox_sales_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSaleOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaleOrderResponse) ProtoMessage() {}

func (x *GetSaleOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sales_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaleOrderResponse.ProtoReflect.Descriptor instead.
func (*GetSaleOrderResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_sales_v1_proto_rawDescGZIP(), []int{1}
}

func (x *GetSaleOrderResponse) GetSaleOrder() *SaleOrder {
	if x != nil {
		return x.SaleOrder
	}
	return nil
}

type GetSaleOrdersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *GetSaleOrdersRequest) Reset() {
	*x = GetSaleOrdersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sandbox_sales_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSaleOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaleOrdersRequest) ProtoMessage() {}

func (x *GetSaleOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sales_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaleOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetSaleOrdersRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_sales_v1_proto_rawDescGZIP(), []int{2}
}

func (x *GetSaleOrdersRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetSaleOrdersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SaleOrders []*SaleOrder `protobuf:"bytes,1,rep,name=sale_orders,json=saleOrders,proto3" json:"sale_orders,omitempty"`
}

func (x *GetSaleOrdersResponse) Reset() {
	*x = GetSaleOrdersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sandbox_sales_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSaleOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSaleOrdersResponse) ProtoMessage() {}

func (x *GetSaleOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sales_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSaleOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetSaleOrdersResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_sales_v1_proto_rawDescGZIP(), []int{3}
}

func (x *GetSaleOrdersResponse) GetSaleOrders() []*SaleOrder {
	if x != nil {
		return x.SaleOrders
	}
	return nil
}

type CreateSaleOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email         string     `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	PaymentMethod string     `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Products      []*Product `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *CreateSaleOrderRequest) Reset() {
	*x = CreateSaleOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sandbox_sales_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSaleOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSaleOrderRequest) ProtoMessage() {}

func (x *CreateSaleOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sales_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSaleOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateSaleOrderRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_sales_v1_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSaleOrderRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateSaleOrderRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreateSaleOrderRequest) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type CreateSaleOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SaleOrder *SaleOrder `protobuf:"bytes,1,opt,name=sale_order,json=saleOrder,proto3" json:"sale_order,omitempty"`
}

func (x *CreateSaleOrderResponse) Reset() {
	*x = CreateSaleOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sandbox_sales_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSaleOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSaleOrderResponse) ProtoMessage() {}

func (x *CreateSaleOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sales_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSaleOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateSaleOrderResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_sales_v1_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSaleOrderResponse) GetSaleOrder() *SaleOrder {
	if x != nil {
		return x.SaleOrder
	}
	return nil
}

type SaleOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PaymentMethod string               `protobuf:"bytes,3,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	OrderDate     *timestamp.Timestamp `protobuf:"bytes,4,opt,name=order_date,json=orderDate,proto3" json:"order_date,omitempty"`
	Products      []*Product           `protobuf:"bytes,5,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *SaleOrder) Reset() {
	*x = SaleOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sandbox_sales_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaleOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaleOrder) ProtoMessage() {}

func (x *SaleOrder) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sales_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaleOrder.ProtoReflect.Descriptor instead.
func (*SaleOrder) Descriptor() ([]byte, []int) {
	return file_sandbox_sales_v1_proto_rawDescGZIP(), []int{6}
}

func (x *SaleOrder) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaleOrder) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SaleOrder) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *SaleOrder) GetOrderDate() *timestamp.Timestamp {
	if x != nil {
		return x.OrderDate
	}
	return nil
}

func (x *SaleOrder) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Quantity int32  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *Product) Reset() {
	*x = Product{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sandbox_sales_v1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_sales_v1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_sandbox_sales_v1_proto_rawDescGZIP(), []int{7}
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_sandbox_sales_v1_proto protoreflect.FileDescriptor

var file_sandbox_sales_v1_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x5f, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x5f,
	0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x78, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x53, 0x61, 0x6c, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x52, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6c, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x73, 0x61,
	0x6c, 0x65, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x61, 0x6c, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x09, 0x73, 0x61, 0x6c,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x2c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6c,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x22, 0x55, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6c, 0x65, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a,
	0x0b, 0x73, 0x61, 0x6c, 0x65, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x73, 0x61, 0x6c,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x6c, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x0a, 0x73, 0x61, 0x6c, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x22, 0x8c, 0x01, 0x0a, 0x16,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6c, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x25, 0x0a, 0x0e,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e,
	0x73, 0x61, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x22, 0x55, 0x0a, 0x17, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6c, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x73, 0x61, 0x6c, 0x65, 0x5f, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x6c,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x09, 0x73, 0x61, 0x6c, 0x65, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x22, 0xca, 0x01, 0x0a, 0x09, 0x53, 0x61, 0x6c, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x39, 0x0a, 0x0a,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x44, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x78, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x22, 0x39,
	0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x32, 0xbb, 0x02, 0x0a, 0x10, 0x53, 0x61,
	0x6c, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6c, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x25,
	0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6c, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e,
	0x73, 0x61, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6c, 0x65,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6c, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x26,
	0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6c, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78,
	0x2e, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x61, 0x6c,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x66, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6c, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x28, 0x2e, 0x73, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x73, 0x61, 0x6c,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6c, 0x65,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x73,
	0x61, 0x6e, 0x64, 0x62, 0x6f, 0x78, 0x2e, 0x73, 0x61, 0x6c, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x61, 0x6c, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sandbox_sales_v1_proto_rawDescOnce sync.Once
	file_sandbox_sales_v1_proto_rawDescData = file_sandbox_sales_v1_proto_rawDesc
)

func file_sandbox_sales_v1_proto_rawDescGZIP() []byte {
	file_sandbox_sales_v1_proto_rawDescOnce.Do(func() {
		file_sandbox_sales_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_sandbox_sales_v1_proto_rawDescData)
	})
	return file_sandbox_sales_v1_proto_rawDescData
}

var file_sandbox_sales_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sandbox_sales_v1_proto_goTypes = []interface{}{
	(*GetSaleOrderRequest)(nil),     // 0: sandbox.sales.v1.GetSaleOrderRequest
	(*GetSaleOrderResponse)(nil),    // 1: sandbox.sales.v1.GetSaleOrderResponse
	(*GetSaleOrdersRequest)(nil),    // 2: sandbox.sales.v1.GetSaleOrdersRequest
	(*GetSaleOrdersResponse)(nil),   // 3: sandbox.sales.v1.GetSaleOrdersResponse
	(*CreateSaleOrderRequest)(nil),  // 4: sandbox.sales.v1.CreateSaleOrderRequest
	(*CreateSaleOrderResponse)(nil), // 5: sandbox.sales.v1.CreateSaleOrderResponse
	(*SaleOrder)(nil),               // 6: sandbox.sales.v1.SaleOrder
	(*Product)(nil),                 // 7: sandbox.sales.v1.Product
	(*timestamp.Timestamp)(nil),     // 8: google.protobuf.Timestamp
}
var file_sandbox_sales_v1_proto_depIdxs = []int32{
	6, // 0: sandbox.sales.v1.GetSaleOrderResponse.sale_order:type_name -> sandbox.sales.v1.SaleOrder
	6, // 1: sandbox.sales.v1.GetSaleOrdersResponse.sale_orders:type_name -> sandbox.sales.v1.SaleOrder
	7, // 2: sandbox.sales.v1.CreateSaleOrderRequest.products:type_name -> sandbox.sales.v1.Product
	6, // 3: sandbox.sales.v1.CreateSaleOrderResponse.sale_order:type_name -> sandbox.sales.v1.SaleOrder
	8, // 4: sandbox.sales.v1.SaleOrder.order_date:type_name -> google.protobuf.Timestamp
	7, // 5: sandbox.sales.v1.SaleOrder.products:type_name -> sandbox.sales.v1.Product
	0, // 6: sandbox.sales.v1.SaleOrderService.GetSaleOrder:input_type -> sandbox.sales.v1.GetSaleOrderRequest
	2, // 7: sandbox.sales.v1.SaleOrderService.GetSaleOrders:input_type -> sandbox.sales.v1.GetSaleOrdersRequest
	4, // 8: sandbox.sales.v1.SaleOrderService.CreateSaleOrder:input_type -> sandbox.sales.v1.CreateSaleOrderRequest
	1, // 9: sandbox.sales.v1.SaleOrderService.GetSaleOrder:output_type -> sandbox.sales.v1.GetSaleOrderResponse
	3, // 10: sandbox.sales.v1.SaleOrderService.GetSaleOrders:output_type -> sandbox.sales.v1.GetSaleOrdersResponse
	5, // 11: sandbox.sales.v1.SaleOrderService.CreateSaleOrder:output_type -> sandbox.sales.v1.CreateSaleOrderResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_sandbox_sales_v1_proto_init() }
func file_sandbox_sales_v1_proto_init() {
	if File_sandbox_sales_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sandbox_sales_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSaleOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sandbox_sales_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSaleOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sandbox_sales_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSaleOrdersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sandbox_sales_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSaleOrdersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sandbox_sales_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSaleOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sandbox_sales_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSaleOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sandbox_sales_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaleOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sandbox_sales_v1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Product); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sandbox_sales_v1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_sales_v1_proto_goTypes,
		DependencyIndexes: file_sandbox_sales_v1_proto_depIdxs,
		MessageInfos:      file_sandbox_sales_v1_proto_msgTypes,
	}.Build()
	File_sandbox_sales_v1_proto = out.File
	file_sandbox_sales_v1_proto_rawDesc = nil
	file_sandbox_sales_v1_proto_goTypes = nil
	file_sandbox_sales_v1_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SaleOrderServiceClient is the client API for SaleOrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SaleOrderServiceClient interface {
	GetSaleOrder(ctx context.Context, in *GetSaleOrderRequest, opts ...grpc.CallOption) (*GetSaleOrderResponse, error)
	GetSaleOrders(ctx context.Context, in *GetSaleOrdersRequest, opts ...grpc.CallOption) (*GetSaleOrdersResponse, error)
	CreateSaleOrder(ctx context.Context, in *CreateSaleOrderRequest, opts ...grpc.CallOption) (*CreateSaleOrderResponse, error)
}

type saleOrderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSaleOrderServiceClient(cc grpc.ClientConnInterface) SaleOrderServiceClient {
	return &saleOrderServiceClient{cc}
}

func (c *saleOrderServiceClient) GetSaleOrder(ctx context.Context, in *GetSaleOrderRequest, opts ...grpc.CallOption) (*GetSaleOrderResponse, error) {
	out := new(GetSaleOrderResponse)
	err := c.cc.Invoke(ctx, "/sandbox.sales.v1.SaleOrderService/GetSaleOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saleOrderServiceClient) GetSaleOrders(ctx context.Context, in *GetSaleOrdersRequest, opts ...grpc.CallOption) (*GetSaleOrdersResponse, error) {
	out := new(GetSaleOrdersResponse)
	err := c.cc.Invoke(ctx, "/sandbox.sales.v1.SaleOrderService/GetSaleOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *saleOrderServiceClient) CreateSaleOrder(ctx context.Context, in *CreateSaleOrderRequest, opts ...grpc.CallOption) (*CreateSaleOrderResponse, error) {
	out := new(CreateSaleOrderResponse)
	err := c.cc.Invoke(ctx, "/sandbox.sales.v1.SaleOrderService/CreateSaleOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SaleOrderServiceServer is the server API for SaleOrderService service.
type SaleOrderServiceServer interface {
	GetSaleOrder(context.Context, *GetSaleOrderRequest) (*GetSaleOrderResponse, error)
	GetSaleOrders(context.Context, *GetSaleOrdersRequest) (*GetSaleOrdersResponse, error)
	CreateSaleOrder(context.Context, *CreateSaleOrderRequest) (*CreateSaleOrderResponse, error)
}

// UnimplementedSaleOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSaleOrderServiceServer struct {
}

func (*UnimplementedSaleOrderServiceServer) GetSaleOrder(context.Context, *GetSaleOrderRequest) (*GetSaleOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSaleOrder not implemented")
}
func (*UnimplementedSaleOrderServiceServer) GetSaleOrders(context.Context, *GetSaleOrdersRequest) (*GetSaleOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSaleOrders not implemented")
}
func (*UnimplementedSaleOrderServiceServer) CreateSaleOrder(context.Context, *CreateSaleOrderRequest) (*CreateSaleOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSaleOrder not implemented")
}

func RegisterSaleOrderServiceServer(s *grpc.Server, srv SaleOrderServiceServer) {
	s.RegisterService(&_SaleOrderService_serviceDesc, srv)
}

func _SaleOrderService_GetSaleOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSaleOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleOrderServiceServer).GetSaleOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sandbox.sales.v1.SaleOrderService/GetSaleOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleOrderServiceServer).GetSaleOrder(ctx, req.(*GetSaleOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaleOrderService_GetSaleOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSaleOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleOrderServiceServer).GetSaleOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sandbox.sales.v1.SaleOrderService/GetSaleOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleOrderServiceServer).GetSaleOrders(ctx, req.(*GetSaleOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SaleOrderService_CreateSaleOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSaleOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaleOrderServiceServer).CreateSaleOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sandbox.sales.v1.SaleOrderService/CreateSaleOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaleOrderServiceServer).CreateSaleOrder(ctx, req.(*CreateSaleOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SaleOrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.sales.v1.SaleOrderService",
	HandlerType: (*SaleOrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSaleOrder",
			Handler:    _SaleOrderService_GetSaleOrder_Handler,
		},
		{
			MethodName: "GetSaleOrders",
			Handler:    _SaleOrderService_GetSaleOrders_Handler,
		},
		{
			MethodName: "CreateSaleOrder",
			Handler:    _SaleOrderService_CreateSaleOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sandbox_sales_v1.proto",
}
